//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecocell.Exceptions {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessage() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ecocell.Exceptions.ResourceErrorMessage", typeof(ResourceErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The company name must have at most 100 (one hundred) characters..
        /// </summary>
        public static string COMPANY_NAME_MAX_LENGTH {
            get {
                return ResourceManager.GetString("COMPANY_NAME_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The document must have at most 14 (fourteen) characters..
        /// </summary>
        public static string DOCUMENT_MAX_LENGTH {
            get {
                return ResourceManager.GetString("DOCUMENT_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The document must have at least 11 (eleven) characters..
        /// </summary>
        public static string DOCUMENT_MIN_LENGTH {
            get {
                return ResourceManager.GetString("DOCUMENT_MIN_LENGTH", resourceCulture);
            }
        }        

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The document is required..
        /// </summary>
        public static string EMPTY_DOCUMENT {
            get {
                return ResourceManager.GetString("EMPTY_DOCUMENT", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The discarding field is required..
        /// </summary>
        public static string EMPTY_DISCARDING_FIELD {
            get {
                return ResourceManager.GetString("EMPTY_DISCARDING_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The email must have at most 50 (fifty) characters..
        /// </summary>
        public static string EMAIL_MAX_LENGTH {
            get {
                return ResourceManager.GetString("EMAIL_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The cellphone number is required..
        /// </summary>
        public static string EMPTY_CELLPHONE {
            get {
                return ResourceManager.GetString("EMPTY_CELLPHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The company name is required..
        /// </summary>
        public static string EMPTY_COMPANY_NAME {
            get {
                return ResourceManager.GetString("EMPTY_COMPANY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The email is required..
        /// </summary>
        public static string EMPTY_EMAIL {
            get {
                return ResourceManager.GetString("EMPTY_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The password is required..
        /// </summary>
        public static string EMPTY_PASSWORD {
            get {
                return ResourceManager.GetString("EMPTY_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The user name is required..
        /// </summary>
        public static string EMPTY_USER_NAME {
            get {
                return ResourceManager.GetString("EMPTY_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The cellphone number must be in fortmat XX X XXXXXXXX.
        /// </summary>
        public static string INVALID_CELLPHONE {
            get {
                return ResourceManager.GetString("INVALID_CELLPHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The email is invalid..
        /// </summary>
        public static string INVALID_EMAIL {
            get {
                return ResourceManager.GetString("INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The password must have at most 20 (twenty) characters..
        /// </summary>
        public static string PASSWORD_MAX_LENGTH {
            get {
                return ResourceManager.GetString("PASSWORD_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The password must have at least 8 (eight) characters..
        /// </summary>
        public static string PASSWORD_MIN_LENGTH {
            get {
                return ResourceManager.GetString("PASSWORD_MIN_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The birth date can not be greater than actual date..
        /// </summary>
        public static string INVALID_BIRTH_DATE {
            get {
                return ResourceManager.GetString("INVALID_BIRTH_DATE", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The birth date must be greater than 08 (eight) years..
        /// </summary>
        public static string INVALID_MIN_BIRTH_DATE {
            get {
                return ResourceManager.GetString("INVALID_MIN_BIRTH_DATE", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unknown error..
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The user name must have at most 100 (one hundred) characters..
        /// </summary>
        public static string USER_NAME_MAX_LENGTH {
            get {
                return ResourceManager.GetString("USER_NAME_MAX_LENGTH", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The user type is invalid..
        /// </summary>
        public static string INVALID_USER_TYPE {
            get {
                return ResourceManager.GetString("INVALID_USER_TYPE", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The informed email already exists..
        /// </summary>
        public static string EMAIL_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("EMAIL_ALREADY_EXISTS", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The informed document already exists..
        /// </summary>
        public static string DOCUMENT_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("DOCUMENT_ALREADY_EXISTS", resourceCulture);
            }
        }
    }
}
