sonar.projectKey=Wandersonrp_ecocell
sonar.organization=wandersonrp
sonar.sources=src
sonar.tests=tests
sonar.cs.opencover.reportsPaths=coverage/**/coverage.opencover.xml
sonar.exclusions=**/appsettings.Example.json,**/Migrations/**
sonar.coverage.exclusions=**/appsettings.Example.json,**/Migrations/**
